// Mocks generated by Mockito 5.0.8 from annotations
// in ditonton/test/helpers/test_helper.dart.
// Do not manually edit this file.

import 'dart:async' as _i17;
import 'dart:convert' as _i8;
import 'dart:typed_data' as _i9;

import 'package:core/core.dart' as _i15;
import 'package:dartz/dartz.dart' as _i12;
import 'package:http/src/base_request.dart' as _i6;
import 'package:http/src/io_client.dart' as _i3;
import 'package:http/src/io_streamed_response.dart' as _i13;
import 'package:http/src/response.dart' as _i14;
import 'package:mockito/mockito.dart' as _i11;
import 'package:movies/domain/entities/movie.dart' as _i19;
import 'package:tv_series/domain/entities/tv_series.dart' as _i1;
import 'package:movies/domain/entities/movie_detail.dart' as _i0;
import 'package:tv_series/domain/entities/tv_series_detail.dart' as _i2;
import 'package:movies/domain/repositories/movie_repository.dart' as _i17;
import 'package:tv_series/domain/repositories/tv_series_repository.dart' as _i4;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeEither<L, R> extends _i11.Fake implements _i12.Either<L, R> {}

class _FakeResponse extends _i11.Fake implements _i14.Response {}

class _FakeIOStreamedResponse extends _i11.Fake
    implements _i13.IOStreamedResponse {}

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i11.Mock implements _i17.MovieRepository {
  MockMovieRepository() {
    _i11.throwOnMissingStub(this);
  }

  @override
  _i17.Future<_i12.Either<_i15.Failure, List<_i19.Movie>>> getNowPlayingMovies() =>
      (super.noSuchMethod(Invocation.method(#getNowPlayingMovies, []),
          returnValue: Future<_i12.Either<_i15.Failure, List<_i19.Movie>>>.value(
              _FakeEither<_i15.Failure, List<_i19.Movie>>())) as _i17.Future<_i12.Either<_i15.Failure, List<_i19.Movie>>>);
  @override
  _i17.Future<_i12.Either<_i15.Failure, List<_i19.Movie>>> getPopularMovies() =>
      (super.noSuchMethod(Invocation.method(#getPopularMovies, []),
          returnValue: Future<_i12.Either<_i15.Failure, List<_i19.Movie>>>.value(
              _FakeEither<_i15.Failure, List<_i19.Movie>>())) as _i17.Future<_i12.Either<_i15.Failure, List<_i19.Movie>>>);
  @override
  _i17.Future<_i12.Either<_i15.Failure, List<_i19.Movie>>> getTopRatedMovies() =>
      (super.noSuchMethod(Invocation.method(#getTopRatedMovies, []),
          returnValue: Future<_i12.Either<_i15.Failure, List<_i19.Movie>>>.value(
              _FakeEither<_i15.Failure, List<_i19.Movie>>())) as _i17.Future<_i12.Either<_i15.Failure, List<_i19.Movie>>>);
  @override
  _i17.Future<_i12.Either<_i15.Failure, _i0.MovieDetail>> getMovieDetail(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieDetail, [id]),
          returnValue: Future<_i12.Either<_i15.Failure, _i0.MovieDetail>>.value(
              _FakeEither<_i15.Failure, _i0.MovieDetail>())) as _i17.Future<_i12.Either<_i15.Failure, _i0.MovieDetail>>);
  @override
  _i17.Future<_i12.Either<_i15.Failure, List<_i19.Movie>>> getMovieRecommendations(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieRecommendations, [id]),
          returnValue: Future<_i12.Either<_i15.Failure, List<_i19.Movie>>>.value(
              _FakeEither<_i15.Failure, List<_i19.Movie>>())) as _i17.Future<_i12.Either<_i15.Failure, List<_i19.Movie>>>);
  @override
  _i17.Future<_i12.Either<_i15.Failure, List<_i19.Movie>>> searchMovies(
          String? query) =>
      (super.noSuchMethod(Invocation.method(#searchMovies, [query]),
          returnValue: Future<_i12.Either<_i15.Failure, List<_i19.Movie>>>.value(
              _FakeEither<_i15.Failure, List<_i19.Movie>>())) as _i17.Future<_i12.Either<_i15.Failure, List<_i19.Movie>>>);
  @override
  _i17.Future<_i12.Either<_i15.Failure, String>> saveWatchlist(
          _i0.MovieDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#saveWatchlist, [movie]),
              returnValue: Future<_i12.Either<_i15.Failure, String>>.value(
                  _FakeEither<_i15.Failure, String>()))
          as _i17.Future<_i12.Either<_i15.Failure, String>>);
  @override
  _i17.Future<_i12.Either<_i15.Failure, String>> removeWatchlist(
          _i0.MovieDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlist, [movie]),
              returnValue: Future<_i12.Either<_i15.Failure, String>>.value(
                  _FakeEither<_i15.Failure, String>()))
          as _i17.Future<_i12.Either<_i15.Failure, String>>);
  @override
  _i17.Future<bool> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(Invocation.method(#isAddedToWatchlist, [id]),
          returnValue: Future<bool>.value(false)) as _i17.Future<bool>);
  @override
  _i17.Future<_i12.Either<_i15.Failure, List<_i19.Movie>>> getWatchlistMovies() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistMovies, []),
          returnValue: Future<_i12.Either<_i15.Failure, List<_i19.Movie>>>.value(
              _FakeEither<_i15.Failure, List<_i19.Movie>>())) as _i17.Future<_i12.Either<_i15.Failure, List<_i19.Movie>>>);
}

/// A class which mocks [TvSeriesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesRepository extends _i11.Mock implements _i4.TvSeriesRepository {
  MockTvSeriesRepository() {
    _i11.throwOnMissingStub(this);
  }

  @override
  _i17.Future<_i12.Either<_i15.Failure, List<_i1.TvSeries>>> getNowPlayingTvSeries() =>
      (super.noSuchMethod(Invocation.method(#getNowPlayingTvSeries, []),
              returnValue: Future<_i12.Either<_i15.Failure, List<_i1.TvSeries>>>.value(
                  _FakeEither<_i15.Failure, List<_i1.TvSeries>>())) as _i17.Future<_i12.Either<_i15.Failure, List<_i1.TvSeries>>>);
  @override
  _i17.Future<_i12.Either<_i15.Failure, List<_i1.TvSeries>>> getPopularTvSeries() =>
      (super.noSuchMethod(Invocation.method(#getPopularTvSeries, []),
              returnValue: Future<_i12.Either<_i15.Failure, List<_i1.TvSeries>>>.value(
                  _FakeEither<_i15.Failure, List<_i1.TvSeries>>())) as _i17.Future<_i12.Either<_i15.Failure, List<_i1.TvSeries>>>);
  @override
  _i17.Future<_i12.Either<_i15.Failure, List<_i1.TvSeries>>> getTopRatedTvSeries() =>
      (super.noSuchMethod(Invocation.method(#getTopRatedTvSeries, []),
              returnValue: Future<_i12.Either<_i15.Failure, List<_i1.TvSeries>>>.value(
                  _FakeEither<_i15.Failure, List<_i1.TvSeries>>())) as _i17.Future<_i12.Either<_i15.Failure, List<_i1.TvSeries>>>);
  @override
  _i17.Future<_i12.Either<_i15.Failure, _i2.TvSeriesDetail>> getTvSeriesDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvSeriesDetail, [id]),
              returnValue: Future<_i12.Either<_i15.Failure, _i2.TvSeriesDetail>>.value(
                  _FakeEither<_i15.Failure, _i2.TvSeriesDetail>())) as _i17.Future<_i12.Either<_i15.Failure, _i2.TvSeriesDetail>>);
  @override
  _i17.Future<_i12.Either<_i15.Failure, List<_i1.TvSeries>>> getTvSeriesRecommendations(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvSeriesRecommendations, [id]),
              returnValue: Future<_i12.Either<_i15.Failure, List<_i1.TvSeries>>>.value(
                  _FakeEither<_i15.Failure, List<_i1.TvSeries>>())) as _i17.Future<_i12.Either<_i15.Failure, List<_i1.TvSeries>>>);
  @override
  _i17.Future<_i12.Either<_i15.Failure, List<_i1.TvSeries>>> searchTvSeries(String? query) =>
      (super.noSuchMethod(Invocation.method(#searchTvSeries, [query]),
              returnValue: Future<_i12.Either<_i15.Failure, List<_i1.TvSeries>>>.value(
                  _FakeEither<_i15.Failure, List<_i1.TvSeries>>())) as _i17.Future<_i12.Either<_i15.Failure, List<_i1.TvSeries>>>);
  @override
  _i17.Future<_i12.Either<_i15.Failure, String>> saveWatchlist(
          _i2.TvSeriesDetail? tvSeries) =>
      (super.noSuchMethod(Invocation.method(#saveWatchlist, [tvSeries]),
              returnValue: Future<_i12.Either<_i15.Failure, String>>.value(
                  _FakeEither<_i15.Failure, String>()))
          as _i17.Future<_i12.Either<_i15.Failure, String>>);
  @override
  _i17.Future<_i12.Either<_i15.Failure, String>> removeWatchlist(
          _i2.TvSeriesDetail? tvSeries) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlist, [tvSeries]),
              returnValue: Future<_i12.Either<_i15.Failure, String>>.value(
                  _FakeEither<_i15.Failure, String>()))
          as _i17.Future<_i12.Either<_i15.Failure, String>>);
  @override
  _i17.Future<bool> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(Invocation.method(#isAddedToWatchlist, [id]),
          returnValue: Future<bool>.value(false)) as _i17.Future<bool>);
  @override
  _i17.Future<_i12.Either<_i15.Failure, List<_i1.TvSeries>>> getWatchlistTvSeries() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistTvSeries, []),
              returnValue: Future<_i12.Either<_i15.Failure, List<_i1.TvSeries>>>.value(
                  _FakeEither<_i15.Failure, List<_i1.TvSeries>>()))
          as _i17.Future<_i12.Either<_i15.Failure, List<_i1.TvSeries>>>);
}

/// A class which mocks [IOClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockIOClient extends _i11.Mock implements _i3.IOClient {
  MockIOClient() {
    _i11.throwOnMissingStub(this);
  }

  @override
  _i17.Future<_i13.IOStreamedResponse> send(_i6.BaseRequest? request) =>
      (super.noSuchMethod(Invocation.method(#send, [request]),
              returnValue: Future<_i13.IOStreamedResponse>.value(
                  _FakeIOStreamedResponse()))
          as _i17.Future<_i13.IOStreamedResponse>);
  @override
  void close() => super.noSuchMethod(Invocation.method(#close, []),
      returnValueForMissingStub: null);
  @override
  _i17.Future<_i14.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#head, [url], {#headers: headers}),
              returnValue: Future<_i14.Response>.value(_FakeResponse()))
          as _i17.Future<_i14.Response>);
  @override
  _i17.Future<_i14.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#get, [url], {#headers: headers}),
              returnValue: Future<_i14.Response>.value(_FakeResponse()))
          as _i17.Future<_i14.Response>);
  @override
  _i17.Future<_i14.Response> post(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i8.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#post, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i14.Response>.value(_FakeResponse()))
          as _i17.Future<_i14.Response>);
  @override
  _i17.Future<_i14.Response> put(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i8.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#put, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i14.Response>.value(_FakeResponse()))
          as _i17.Future<_i14.Response>);
  @override
  _i17.Future<_i14.Response> patch(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i8.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#patch, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i14.Response>.value(_FakeResponse()))
          as _i17.Future<_i14.Response>);
  @override
  _i17.Future<_i14.Response> delete(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i8.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#delete, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i14.Response>.value(_FakeResponse()))
          as _i17.Future<_i14.Response>);
  @override
  _i17.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#read, [url], {#headers: headers}),
          returnValue: Future<String>.value('')) as _i17.Future<String>);
  @override
  _i17.Future<_i9.Uint8List> readBytes(Uri? url,
          {Map<String, String>? headers}) =>
      (super.noSuchMethod(
              Invocation.method(#readBytes, [url], {#headers: headers}),
              returnValue: Future<_i9.Uint8List>.value(_i9.Uint8List(0)))
          as _i17.Future<_i9.Uint8List>);
  @override
  String toString() => super.toString();
}
